name: "IBM Mobile Foundation Developer Center"
description: "Develop, test, manage, and secure your native and hybrid apps. Use the labs, blog posts, tutorials and videos to learn about Mobile Foundation on IBM Cloud or on-premise. Download product components and samples related to Mobile Foundation."
url: https://mobilefirstplatform.ibmcloud.com
languages: ["de", "en", "es", "fr", "ja", "ko", "pt-br", "ru", "zh-hans", "it"]
defaultLanguage: en
languageNames:
  de: Deutsch
  en: English
  es: Spanish
  fr: French
  ja: Japanese
  ko: Korean
  pt-br: Portugese
  ru: Russian
  it: Italian
  zh-hans: Chinese
source_url: https://github.ibm.com/MFPSamples/DevCenter
permalink: pretty
paginate: 40
paginate_path: "/blog/:num/"
markdown: kramdown
generate_redirects: false
print_pdf: false
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
      show_disqus: true
      pinned: false
      indexed: true
  -
    scope:
      path: "blog/rss"
    values:
      indexed: false
  -
    scope:
      path: "feed.xml"
    values:
      indexed: false
  -
    scope:
      path: "js"
    values:
      indexed: false
  -
    scope:
      path: "css"
    values:
      indexed: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      category: page
      indexed: true
  -
    scope:
      path: "tutorials/en"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/de"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/es"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/fr"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/ja"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/ko"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/pt-br/"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/ru"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/zh-hans/"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "tutorials/it/"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "labs"
    values:
      layout: labs
      show_disqus: true
      category: lab
  -
    scope:
      path: "pdf"
    values:
      layout: pdflist
      permalink: /:path/:basename:output_ext
      indexed: false
